[package]
name = "expression-language"
version = "0.1.0"
authors = ["Roland Brand <rolandbrand11@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
lazy_static = "1.4.0"
libc = "0.2.66"

[lib]
crate-type = ["cdylib"]
